### ISSUE TITLE
 waitting for the code to open source...

### ISSUE THREAD

**Issue by 7yzx** [caodinhduc/X-PDNet-official#1]
Thank you for your tremendous efforts.

**Comment by caodinhduc** [comment]
Hello, I am re-training this model on ScanNet, It may be updated after the new year holiday, lets back again

**Comment by caodinhduc** [comment]
I just update the code of X-PDNet model trained on ScanNet dataset without Depth Guided Boundary Preserving Loss, the model retrained with DGBPL will be updated soon
